// Writes firebase-config.js and posthog-config.js from environment variables.
// - On Vercel: runs as the build command and reads the project's Environment Variables.
// - Locally:   `node scripts/build-config.mjs` reads them from .env.
// Accepts FIREBASE_API_KEY or API_KEY style names. Missing values => analytics stays off.
// PostHog: POSTHOG_KEY (project API key, phc_...) and optional POSTHOG_HOST (defaults to US cloud).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Load .env for local runs (Vercel provides real env vars, which take precedence).
const envFile = path.join(root, ".env");
if (existsSync(envFile)) {
  for (const line of readFileSync(envFile, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

const read = (name) => process.env[`FIREBASE_${name}`] ?? process.env[name] ?? "";
const config = {
  apiKey: read("API_KEY"),
  authDomain: read("AUTH_DOMAIN"),
  projectId: read("PROJECT_ID"),
  storageBucket: read("STORAGE_BUCKET"),
  messagingSenderId: read("MESSAGING_SENDER_ID"),
  appId: read("APP_ID"),
  measurementId: read("MEASUREMENT_ID"),
};

writeFileSync(
  path.join(root, "firebase-config.js"),
  `// Generated by scripts/build-config.mjs from environment variables - do not edit or commit.\n` +
    `export const firebaseConfig = ${JSON.stringify(config, null, 2)};\n`,
);

const missing = Object.entries(config).filter(([, v]) => !v).map(([k]) => k);
console.log(missing.length ? `firebase-config.js written; missing: ${missing.join(", ")} (analytics off)` : "firebase-config.js written (analytics on)");

const posthogConfig = {
  key: process.env.POSTHOG_KEY ?? "",
  host: process.env.POSTHOG_HOST || "https://us.i.posthog.com",
};

writeFileSync(
  path.join(root, "posthog-config.js"),
  `// Generated by scripts/build-config.mjs from environment variables - do not edit or commit.\n` +
    `export const posthogConfig = ${JSON.stringify(posthogConfig, null, 2)};\n`,
);

console.log(posthogConfig.key ? `posthog-config.js written (PostHog on, ${posthogConfig.host})` : "posthog-config.js written; missing: POSTHOG_KEY (PostHog off)");
